# Generated by Django 4.2 on 2023-04-30 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('buyer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='buyer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, upload_to='photos/')),
                ('bio', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('facebook_profile', models.URLField(blank=True)),
                ('twitter_profile', models.URLField(blank=True)),
                ('instagram_profile', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Buyer Profiles',
            },
        ),
    ]
