# Generated by Django 4.2 on 2023-05-02 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_owner', '0001_initial'),
        ('buyers', '0002_buyerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='saved_properties',
            field=models.ManyToManyField(related_name='saved', to='property_owner.propertylisting'),
        ),
        migrations.AlterField(
            model_name='buyerreview',
            name='ratings',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
